import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";

const inter = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Foolideas",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div
          style={{
            position: "fixed",
            top: 0,
            left: 0,
            width: "100%",
            zIndex: 99,
          }}
        >
          <Navbar />
        </div>

        {/* This spacer div creates room for the fixed navbar */}
        <div style={{ height: "50px" }}></div>

        {children}
      </body>
    </html>
  );
}
